name = "moontv"
compatibility_date = "2025-06-28"

# 指定 Pages 产物目录，供 `wrangler pages dev` 本地预览使用
pages_build_output_dir = ".vercel/output/static"

# 开启 Node.js API 兼容层（next-on-pages 已自动注入所需 polyfill）
compatibility_flags = ["nodejs_compat"] 
# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"              # Worker 代码中使用的变量名
database_name = "moontv"    # D1 数据库名称
# 环境变量（普通变量）
[vars]
NEXT_PUBLIC_STORAGE_TYPE = "d1"
USERNAME = "fyx"
PASSWORD = "jmgtj3689"
